git checkout standard;
make;
./bnb-fs Instancias/i08 params.txt >> tempos/standard_times_1mt10Mn.txt;
./bnb-fs Instancias/i08b params.txt >> tempos/standard_times_1mt10Mn.txt;
./bnb-fs Instancias/i09 params.txt >> tempos/standard_times_1mt10Mn.txt;
./bnb-fs Instancias/i10 params.txt >> tempos/standard_times_1mt10Mn.txt;
./bnb-fs Instancias/i10b params.txt >> tempos/standard_times_1mt10Mn.txt;
./bnb-fs Instancias/i11 params.txt >> tempos/standard_times_1mt10Mn.txt; 
./bnb-fs Instancias/i12 params.txt >> tempos/standard_times_1mt10Mn.txt;
./bnb-fs Instancias/i12b params.txt >> tempos/standard_times_1mt10Mn.txt;
./bnb-fs Instancias/i13 params.txt >> tempos/standard_times_1mt10Mn.txt;
./bnb-fs Instancias/i13b params.txt >> tempos/standard_times_1mt10Mn.txt;
./bnb-fs Instancias/i14 params.txt >> tempos/standard_times_1mt10Mn.txt;
./bnb-fs Instancias/i15 params.txt >> tempos/standard_times_1mt10Mn.txt;
./bnb-fs Instancias/i16 params.txt >> tempos/standard_times_1mt10Mn.txt;
./bnb-fs Instancias/i17 params.txt >> tempos/standard_times_1mt10Mn.txt;
./bnb-fs Instancias/i18 params.txt >> tempos/standard_times_1mt10Mn.txt;
./bnb-fs Instancias/i19 params.txt >> tempos/standard_times_1mt10Mn.txt;
./bnb-fs Instancias/i20 params.txt >> tempos/standard_times_1mt10Mn.txt;
./bnb-fs Instancias/i21 params.txt >> tempos/standard_times_1mt10Mn.txt;
./bnb-fs Instancias/i22 params.txt >> tempos/standard_times_1mt10Mn.txt;
./bnb-fs Instancias/i23 params.txt >> tempos/standard_times_1mt10Mn.txt;
./bnb-fs Instancias/i24 params.txt >> tempos/standard_times_1mt10Mn.txt;
./bnb-fs Instancias/i25 params.txt >> tempos/standard_times_1mt10Mn.txt;
./bnb-fs Instancias/i26 params.txt >> tempos/standard_times_1mt10Mn.txt;
./bnb-fs Instancias/i27 params.txt >> tempos/standard_times_1mt10Mn.txt;
./bnb-fs Instancias/i28 params.txt >> tempos/standard_times_1mt10Mn.txt;
./bnb-fs Instancias/i29 params.txt >> tempos/standard_times_1mt10Mn.txt;
./bnb-fs Instancias/i30 params.txt >> tempos/standard_times_1mt10Mn.txt;
git add . ;
git commit -m "Sent new standard data.";
git push origin standard;

git checkout two_primal;
make;
./bnb-fs Instancias/i08 params.txt >> tempos/two_primal_times_1mt10Mn.txt;
./bnb-fs Instancias/i08b params.txt >> tempos/two_primal_times_1mt10Mn.txt;
./bnb-fs Instancias/i09 params.txt >> tempos/two_primal_times_1mt10Mn.txt;
./bnb-fs Instancias/i10 params.txt >> tempos/two_primal_times_1mt10Mn.txt;
./bnb-fs Instancias/i10b params.txt >> tempos/two_primal_times_1mt10Mn.txt;
./bnb-fs Instancias/i11 params.txt >> tempos/two_primal_times_1mt10Mn.txt; 
./bnb-fs Instancias/i12 params.txt >> tempos/two_primal_times_1mt10Mn.txt;
./bnb-fs Instancias/i12b params.txt >> tempos/two_primal_times_1mt10Mn.txt;
./bnb-fs Instancias/i13 params.txt >> tempos/two_primal_times_1mt10Mn.txt;
./bnb-fs Instancias/i13b params.txt >> tempos/two_primal_times_1mt10Mn.txt;
./bnb-fs Instancias/i14 params.txt >> tempos/two_primal_times_1mt10Mn.txt;
./bnb-fs Instancias/i15 params.txt >> tempos/two_primal_times_1mt10Mn.txt;
./bnb-fs Instancias/i16 params.txt >> tempos/two_primal_times_1mt10Mn.txt;
./bnb-fs Instancias/i17 params.txt >> tempos/two_primal_times_1mt10Mn.txt;
./bnb-fs Instancias/i18 params.txt >> tempos/two_primal_times_1mt10Mn.txt;
./bnb-fs Instancias/i19 params.txt >> tempos/two_primal_times_1mt10Mn.txt;
./bnb-fs Instancias/i20 params.txt >> tempos/two_primal_times_1mt10Mn.txt;
./bnb-fs Instancias/i21 params.txt >> tempos/two_primal_times_1mt10Mn.txt;
./bnb-fs Instancias/i22 params.txt >> tempos/two_primal_times_1mt10Mn.txt;
./bnb-fs Instancias/i23 params.txt >> tempos/two_primal_times_1mt10Mn.txt;
./bnb-fs Instancias/i24 params.txt >> tempos/two_primal_times_1mt10Mn.txt;
./bnb-fs Instancias/i25 params.txt >> tempos/two_primal_times_1mt10Mn.txt;
./bnb-fs Instancias/i26 params.txt >> tempos/two_primal_times_1mt10Mn.txt;
./bnb-fs Instancias/i27 params.txt >> tempos/two_primal_times_1mt10Mn.txt;
./bnb-fs Instancias/i28 params.txt >> tempos/two_primal_times_1mt10Mn.txt;
./bnb-fs Instancias/i29 params.txt >> tempos/two_primal_times_1mt10Mn.txt;
./bnb-fs Instancias/i30 params.txt >> tempos/two_primal_times_1mt10Mn.txt;
git add . ;
git commit -m "Sent new two_primal data.";
git push origin two_primal;

git checkout dominance;
make;
./bnb-fs Instancias/i08 params.txt >> tempos/dominance_times_1mt10Mn.txt;
./bnb-fs Instancias/i08b params.txt >> tempos/dominance_times_1mt10Mn.txt;
./bnb-fs Instancias/i09 params.txt >> tempos/dominance_times_1mt10Mn.txt;
./bnb-fs Instancias/i10 params.txt >> tempos/dominance_times_1mt10Mn.txt;
./bnb-fs Instancias/i10b params.txt >> tempos/dominance_times_1mt10Mn.txt;
./bnb-fs Instancias/i11 params.txt >> tempos/dominance_times_1mt10Mn.txt; 
./bnb-fs Instancias/i12 params.txt >> tempos/dominance_times_1mt10Mn.txt;
./bnb-fs Instancias/i12b params.txt >> tempos/dominance_times_1mt10Mn.txt;
./bnb-fs Instancias/i13 params.txt >> tempos/dominance_times_1mt10Mn.txt;
./bnb-fs Instancias/i13b params.txt >> tempos/dominance_times_1mt10Mn.txt;
./bnb-fs Instancias/i14 params.txt >> tempos/dominance_times_1mt10Mn.txt;
./bnb-fs Instancias/i15 params.txt >> tempos/dominance_times_1mt10Mn.txt;
./bnb-fs Instancias/i16 params.txt >> tempos/dominance_times_1mt10Mn.txt;
./bnb-fs Instancias/i17 params.txt >> tempos/dominance_times_1mt10Mn.txt;
./bnb-fs Instancias/i18 params.txt >> tempos/dominance_times_1mt10Mn.txt;
./bnb-fs Instancias/i19 params.txt >> tempos/dominance_times_1mt10Mn.txt;
./bnb-fs Instancias/i20 params.txt >> tempos/dominance_times_1mt10Mn.txt;
./bnb-fs Instancias/i21 params.txt >> tempos/dominance_times_1mt10Mn.txt;
./bnb-fs Instancias/i22 params.txt >> tempos/dominance_times_1mt10Mn.txt;
./bnb-fs Instancias/i23 params.txt >> tempos/dominance_times_1mt10Mn.txt;
./bnb-fs Instancias/i24 params.txt >> tempos/dominance_times_1mt10Mn.txt;
./bnb-fs Instancias/i25 params.txt >> tempos/dominance_times_1mt10Mn.txt;
./bnb-fs Instancias/i26 params.txt >> tempos/dominance_times_1mt10Mn.txt;
./bnb-fs Instancias/i27 params.txt >> tempos/dominance_times_1mt10Mn.txt;
./bnb-fs Instancias/i28 params.txt >> tempos/dominance_times_1mt10Mn.txt;
./bnb-fs Instancias/i29 params.txt >> tempos/dominance_times_1mt10Mn.txt;
./bnb-fs Instancias/i30 params.txt >> tempos/dominance_times_1mt10Mn.txt;
git add . ;
git commit -m "Sent new dominance data.";
git push origin dominance;